name: Automated Code Review

on:
  pull_request:
    branches:
      - main  # PR이 열릴 때, main 브랜치와 비교하여 코드 리뷰 수행

jobs:
  review:
    runs-on: ubuntu-latest  # 워크플로우가 실행될 환경 설정

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 리포지토리의 코드를 체크아웃

      - name: Install Ollama
        run: |
          curl -sSL https://ollama.com/install.sh | bash  # Ollama 설치

      - name: Install LLM CLI
        run: |
          pip install llm  # LLM CLI 설치

      - name: Download Qwen-2 Model
        run: |
          ollama pull qwen2  # Qwen-2 모델 다운로드

      - name: Run Code Review
        run: |
          git diff main...'${{ github.head_ref }}' | ollama run qwen2 -- "당신은 senior developer입니다. 개발자가 제출한 풀 리퀘스트에서 변경된 다음 파일을 요약합니다. 파일 내의 주요 수정, 추가, 삭제 및 중요한 업데이트에 중점을 두고 요약하세요. 요약에 파일 이름을 포함하지 말고 글머리 기호로 요약을 나열하세요. 문제가 있거나 유지 관리가 까다로운 코드에 대한 조언도 있으면 좋겠습니다. 중요 : 요약에 코드 블록/차이점도 줄 번호와 함께 포함하세요." > review_summary.txt  # 코드 리뷰 실행 후 결과를 파일에 저장

      - name: Upload Review Summary
        uses: actions/upload-artifact@v3  # 결과 파일을 GitHub에 아티팩트로 업로드
        with:
          name: review-summary
          path: review_summary.txt

      - name: Add Review as Pull Request Comment
        uses: mshick/add-pr-comment@v1  # Pull Request에 코드 리뷰 결과를 댓글로 추가
        with:
          message: |
            ## Automated Code Review Summary
            $(cat review_summary.txt)
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
